### ISSUE TITLE
Allow usage of NettyEventLoops

### ISSUE THREAD

**Issue by sobersanta** [AppsFlyer/aerospike-clj#40]
Currently it is not possible to provide com.aerospike.client.async.NettyEventLoop instance when creating new client instance, as internally it uses ^com.aerospike.client.async.NioEventLoop meta hints on bindings.
I believe those meta hints should be replaced with more generic com.aerospike.client.async.EventLoops interface in order to allow alternative implementations.

**Comment by barkanido** [comment]
PR is welcome
