### ISSUE TITLE
Unconditional eventLoops.close() call when stopping client

### ISSUE THREAD

**Issue by sobersanta** [AppsFlyer/aerospike-clj#41]
When closing an aerospike client in `stop-aerospike-client` function, corresponding EventLoops instance is being closed unconditionally, which causes problems when having multiple clients with shared EventLoops instance.
In this case, the lib attempts to close same instance multiple times, which leads to hangs.
I propose to close the client's EventLoops instance only in case it was created automatically by the library, and not closed when an external instance is provided via `:event-loops` configuration parameter - in this case its lifecycle must be managed by a user.

**Comment by barkanido** [comment]
PR is welcome!
