### ISSUE TITLE
Purpose of calling EventPolicy setters on object that is not returned

### ISSUE THREAD

**Issue by predar** [AppsFlyer/aerospike-clj#44]
Hello,

I was taking a closer look at the EventPolicy building function and I noticed that this two setters are called on an object that is never returned.
Is there a purpose for setting these values?

https://github.com/AppsFlyer/aerospike-clj/blob/b9a20784bf8783bf4f87a4e0e68634492845b09c/src/main/clojure/aerospike_clj/policy.clj#L127

https://github.com/AppsFlyer/aerospike-clj/blob/b9a20784bf8783bf4f87a4e0e68634492845b09c/src/main/clojure/aerospike_clj/policy.clj#L128

Thank you,
Preda Radu

**Comment by barkanido** [comment]
Hey, thanks for looking!
this is probably some forgotten code. should be removed.
