### ISSUE TITLE
Running into "Exception in thread "NioEventLoops-0" java.lang.OutOfMemoryError"

### ISSUE THREAD

**Issue by ashwinbhaskar** [AppsFlyer/aerospike-clj#47]
I am trying to make batch updates using `put-multiple`, concurrently. I run into this error

```
Exception in thread "NioEventLoops-0" java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:694)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at com.aerospike.client.async.NioEventLoop.createByteBuffer(NioEventLoop.java:151)
	at com.aerospike.client.async.NioEventLoop.getByteBuffer(NioEventLoop.java:158)
	at com.aerospike.client.async.NioCommand.executeCommand(NioCommand.java:231)
	at com.aerospike.client.async.NioCommand.run(NioCommand.java:194)
	at com.aerospike.client.async.NioEventLoop.registerCommands(NioEventLoop.java:226)
	at com.aerospike.client.async.NioEventLoop.runCommands(NioEventLoop.java:188)
	at com.aerospike.client.async.NioEventLoop.run(NioEventLoop.java:171)
	at java.lang.Thread.run(Thread.java:748)
```

This is my code

```
(defn update-inventory-aero
  [csv-file]
  (trace/span
    "update-inventory"
    (with-open [reader (clojure.java.io/reader csv-file)]
      (let [lines (->> (line-seq reader)
                       (map #(str/split % #",")))]
        (run! (fn [ls]
                (let [[sets indices payloads expirations] (reduce (fn [[sets indices payloads expirations] [id quantity & _]]
                                                                    [(conj sets "inventory")
                                                                     (conj indices id)
                                                                     (conj payloads {"quantity" quantity})
                                                                     (conj expirations -1)])
                                                                  [[] [] [] []]
                                                                  ls)]
                  (aero/put-multiple aero-client indices sets payloads expirations)))
              (partition 250 lines))))))
```

And this function is called using the code below. The size of `files` is `19`
```
(doseq [f files]
  (update-inventory-aero f))
```

I am using the aero client obtained from `init-simple-aerospike-client`

**Comment by barkanido** [comment]
@ashwinbhaskar, what are the sizes of those files (i.e., how many lines)?
`put-multiple` is merely grouping a bunch of async `put`s to a single `CompletableFuture` and returns it. Note that creating a command is a very fast action (compared to waiting for it to finish). The async client is doing its best to throw whatever you have thrown at it on the wire, but this is sometimes not good enough.
To that extent, the async client may appear like a difficult beast to tame. I guess that you are potentially overloading it. You have a few possible approaches here, as I see it:

1. `deref` the future that is returned from, say, every 250 lines (`put` commands). `@(fn [ls] ...`. This will effectively wait for each chunk of lines to be completely handled (and the related memory freed).
2. Write a more involved back-pressure mechanism using `maxCommandsInProcess` and `maxCommandsInQueue` configuration on `EventPolicy`. For complete documentation, read the [JavaDoc](https://aerospike.com/apidocs/java/com/aerospike/client/async/EventPolicy.html). Such a mechanism is outside of the scope of both the underlying Java library and this library.
3. Use the sync client (not used by this library, but in your classpath already)

Does this answer your question?

**Comment by ashwinbhaskar** [comment]
@barkanido Each file contains ~ `50,000` lines. Will go through the documentation you linked. Also, all these 19 files need to be processed concurrently. Using sync client might not be helpful here?

**Comment by barkanido** [comment]
The sync client can be invoked from a pool of threads, that you can control. The real problem here is (missing) backpressure IMO. The async in its default implementation is behaving like an unbound buffer, it just allocated direct memory as much as it can to serve the calling code.
So you _can_ process the files in parallel, you just need to control the throughput.

**Comment by ashwinbhaskar** [comment]
>The sync client can be invoked from a pool of threads, that you can control.

Not able to find the doc/example for this. Can you point me to this?

**Comment by barkanido** [comment]
> > The sync client can be invoked from a pool of threads, that you can control.
> 
> Not able to find the doc/example for this. Can you point me to this?

This is not a feature of the client but rather a way to operate it. The sync API jusy runs on (and blocking the) calling thread. This is unlike the async API that operates on an event loop with its own threads.
