### ISSUE TITLE
Specifying a ClientPolicy throws an error

### ISSUE THREAD

**Issue by ashwinbhaskar** [AppsFlyer/aerospike-clj#48]
I am starting the `aerospike-client` using 
```
(aero/init-simple-aerospike-client ["localhost"] "test" {:enable-logging true
                                                                  :client-policy  (let [client-policy (ClientPolicy.)]
                                                                                    (set! (.maxConnsPerNode client-policy) 600)
                                                                                    client-policy)})
```
I am introducing  `client-policy` to increase the number of connections. But it throws the following error when I try to use the client

```
#error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause #error {
 :cause nilnilnil
 :via
 [
 :via
 [
 :via
 [nil
 :via
 [nilnil
 :via
 [nil
 :via
 [
 :via
 [nil
 :via
 [nil{:type 
 :via
 [nil{:type 
 :via
 [{:type {:type nil
 :via
 [{:type nil{:type 
 :via
 [{:type nil
 :via
 [{:type {:type nil{:type nil
 :via
 [
 :via
 [{:type {:type nil
 :via
 [{:type {:type nil
 :via
 [{:type nil
 :via
 [{:type {:type nil
 :via
 [{:type java.lang.NullPointerException
   :message java.lang.NullPointerExceptionjava.lang.NullPointerExceptionnil
   :message 
   :message java.lang.NullPointerExceptionnil
   :message niljava.lang.NullPointerExceptionnil
   :message niljava.lang.NullPointerExceptionjava.lang.NullPointerException
   :message 
   :message 
   :at nilnil
   :at 
   :at {:type java.lang.NullPointerExceptionjava.lang.NullPointerException
   :message 
   :message nil
   :at nil
   :at java.lang.NullPointerException
   :message java.lang.NullPointerExceptionnil
   :message java.lang.NullPointerExceptionnil
   :message 
   :at niljava.lang.NullPointerException[
   :message [nil[
   :at com.aerospike.client.async.NioCommandjava.lang.NullPointerExceptioncom.aerospike.client.async.NioCommand  <init> <init> [
   :at com.aerospike.client.async.NioCommand <init> [java.lang.NullPointerExceptioncom.aerospike.client.async.NioCommand <init> 
   :message 
   :at nil
   :at java.lang.NullPointerException[[
   :message nilcom.aerospike.client.async.NioCommand
   :at  com.aerospike.client.async.NioCommandjava.lang.NullPointerException[<init>
   :message  nilNioCommand.java
   :at java.lang.NullPointerException 
   :message com.aerospike.client.async.NioCommand[ nil55
   :at com.aerospike.client.async.NioCommandNioCommand.java  <init>[55 
   :at <init>] [}com.aerospike.client.async.NioCommand
   :at [[com.aerospike.client.async.NioCommand com.aerospike.client.async.NioCommand[<init> <init> com.aerospike.client.async.NioCommand NioCommand.java  NioCommand.java<init> 55]55} ]
   :at ]}NioCommand.java ]55
 :trace
```

**Comment by barkanido** [comment]
This comes from the Java client. https://github.com/aerospike/aerospike-client-java/blob/ea84e60c8a6dc70275397afb95b995ee476342bf/client/src/com/aerospike/client/async/NioCommand.java#L55

ClientPolicy is just a POJO and you are misusing it. So you can either reference the Java library examples or follow this library client creation code which does all of the setup for you. Init-simple-aerospike-client also allow passing a subset of the flags you are trying to change in a conf argument map.

And btw, increasing the max number of connections per node will just hide problems from you.

**Comment by ashwinbhaskar** [comment]
>Init-simple-aerospike-client also allow passing a subset of the flags you are trying to change in a conf argument map.

Found this. Can we add this in the comment section of `init-simple-aerospike-client`? Also, why not make it a keyword? I can make the changes and raise a PR, if you are okay with it.

>And btw, increasing the max number of connections per node will just hide problems from you.

I followed your suggestion from the other PR of throttling the number of async requests. I was trying to find the sweet spot of the `maxConnections` after which there is no performance imrpovement.

**Comment by barkanido** [comment]
> Found this. Can we add this in the comment section of `init-simple-aerospike-client`? Also, why not make it a keyword? I can make the changes and raise a PR, if you are okay with it.

The implementation is built with macros and moving it now to keywords both breaks the API and is also even more surprising IMO. But anyway, leaving opinions aside, breaking the API is not a viable option.




> I followed your suggestion from the other PR of throttling the number of async requests. I was trying to find the sweet spot of the `maxConnections` after which there is no performance improvement.

I recommend not touching the `maxConnections`, but rather controlling the `maxCommandsInProcess` which imposes an upper bound on `maxConnections`.

**Comment by barkanido** [comment]
> Can we add this in the comment section of `init-simple-aerospike-client`

A PR is welcome ;-)
